const nome =prompt("Nome Completo")
const dataNascimento =prompt("Data de nascimento (utilize as / )")
let endereco =prompt("Endereço")
const cpf =prompt("CPF")
let escolaridade =prompt("Escolaridade")
let possuiCnh =prompt("possui CNH?")
let quantidadeFilhos =prompt("Quantos filhos possui?")
let cargo =prompt("Cargo atual")
let salario =prompt("Salário")
let comissaoPorcentagem =prompt("Recebe comissão? Se sim, informe a porcentagem, caso não, responda com zero")
const anoAdmissao =prompt("Informe o ano de admissão")

String(dataNascimento)
String(cpf)
String(quantidadeFilhos)
String(salario)
String(comissaoPorcentagem)
String(anoAdmissao)

console.log(typeof nome)
console.log(typeof dataNascimento)
console.log(typeof endereco)
console.log(typeof cpf)
console.log(typeof escolaridade)
console.log(typeof possuiCnh)
console.log(typeof quantidadeFilhos)
console.log(typeof cargo)
console.log(typeof salario)
console.log(typeof comissaoPorcentagem)
console.log(typeof anoAdmissao)

console.log("Nome completo:", nome)
console.log("Data de Nascimento:",dataNascimento)
console.log("Endereço:",endereco)
console.log("CPF:",cpf)
console.log("Escolaridade:",escolaridade)
console.log("CNH:",possuiCnh)
console.log("Quantidade de Filhos:",quantidadeFilhos)
console.log("Cargo Atual:",cargo)
console.log("Salário:",salario)
console.log("Porcentagem de Comissão:",comissaoPorcentagem)
console.log("Ano de Admissão:",anoAdmissao)
